<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;netstandard2.1;netstandard2.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <!-- Global Usings -->
    <ItemGroup>

    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Polyfill" Version="9.4.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Condition="$(TargetFrameworkIdentifier) == '.NETStandard' or $(TargetFrameworkIdentifier) == '.NETFramework'"
                          Include="System.Memory" Version="4.6.3"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ScrubJay.Interpolated\src\ScrubJay.Interpolated.csproj" />
      <ProjectReference Include="..\..\ScrubJay.Universal\src\ScrubJay.Universal.csproj" />
    </ItemGroup>

</Project>
