<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;netstandard2.1;netstandard2.0;net48;</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <!-- NuGet Packages -->
    <ItemGroup>
        <PackageReference Include="Fody">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="InlineIL.Fody">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Polyfill">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
      <Compile Remove="..\..\..\Users\Timothy\.nuget\packages\polyfill\9.9.0\contentFiles\cs\netstandard2.1\Trimming\DynamicDependencyAttribute.cs" />
      <Compile Remove="..\..\..\Users\Timothy\.nuget\packages\polyfill\9.9.0\contentFiles\cs\netstandard2.0\Trimming\DynamicDependencyAttribute.cs" />
    </ItemGroup>

</Project>
