<Project>
	<!-- Common to all Projects -->
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<!-- Generate XML documentation -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<!-- But suppress warnings about undocumented members -->
		<NoWarn>$(NoWarn);CS1591;</NoWarn>
	</PropertyGroup>
	
	<!-- Analysis -->
	<PropertyGroup>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
	
	<!-- NuGet -->
	<PropertyGroup>
		<!-- Each will specify PackageId, PackageVersion, Description, -->
		<Authors>Dissolution</Authors>
		<RepositoryUrl>https://github.com/Dissolution/ScrubJay</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile.
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>
	
	<!-- Release configurations -->
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<!-- Create NuGet Package -->
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<!-- Validate -->
		<EnablePackageValidation>false</EnablePackageValidation>
		<!-- Set common output path for Packages -->
		<PackageOutputPath>..\..\packages\</PackageOutputPath>
	</PropertyGroup>
	
	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<None Include="..\README.md" Pack="true" PackagePath="\"/>
		<None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\"/>
	</ItemGroup>
	
	<!-- global usings -->
	<ItemGroup>
		<Using Include="JetBrains.Annotations"/>
		
		<Using Include="System.Collections"/>
		<Using Include="System.Diagnostics"/>
		<Using Include="System.Diagnostics.CodeAnalysis"/>
		<Using Include="System.Runtime.CompilerServices"/>
		<Using Include="System.Runtime.InteropServices"/>
		<Using Include="System.Text"/>
		<Using Include="System.Numerics"/>
		
		<!-- Aliases -->
		<Using Include="System.ReadOnlySpan&lt;System.Char&gt;" Alias="text"/>
		<Using Include="System.Diagnostics.CodeAnalysis.NotNullAttribute" Alias="NotNullAttribute"/>
	</ItemGroup>
	<!-- global packages -->
	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" PrivateAssets="all"/>
	</ItemGroup>
</Project>

