<Project>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>

        <!-- generate XML documentation files -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <!-- set code analysis rules -->
        <AnalysisLevel>latest</AnalysisLevel>
        <AnalysisMode>All</AnalysisMode>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>


        <!-- Suppress Warnings -->
        <NoWarn>
            $(NoWarn);      <!-- inherit any other suppressions -->
            CS1591;         <!-- undocumented members -->
            CS8981;         <!-- `text` alias -->
            CA1062;
            CA1715;         <!-- Prefix Generic type parameter names with 'T' -->
            CA1063;         <!-- Implement IDisposable 'correctly' -->
            CA1000;         <!-- Do not declare static memebrs on generic types -->
            CA2225;         <!-- Provide alternative methods for operators -->
            CA1710; CA1805; CA1051; CA1815; CA1033; CA1725; CA1810; CA1307; CA1031; CA1305; CA1720;

        </NoWarn>
    </PropertyGroup>

    <!-- Analyzers -->
    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer" Version="2.0.257">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SonarAnalyzer.CSharp" Version="10.16.0.128591">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Analyzers" Version="4.14.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.analyzers" Version="1.26.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <!-- NuGet -->
    <PropertyGroup>
        <Authors>Dissolution</Authors>
        <RepositoryUrl>https://github.com/Dissolution/ScrubJay</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <!-- Release configurations -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <!-- Create NuGet Package -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <!-- Validate -->
        <EnablePackageValidation>false</EnablePackageValidation>
        <!-- Set common output path for Packages -->
        <PackageOutputPath>..\..\packages\</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="..\README.md" Pack="true" PackagePath="\"/>
        <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <!-- global usings -->
    <ItemGroup>
        <Using Include="System.Collections"/>
        <Using Include="System.Diagnostics"/>
        <Using Include="System.Diagnostics.CodeAnalysis"/>
        <Using Include="System.Numerics"/>
        <Using Include="System.Runtime.CompilerServices"/>
        <Using Include="System.Runtime.InteropServices"/>
        <Using Include="System.Text"/>

        <!-- Aliases -->
        <Using Include="System.ReadOnlySpan&lt;System.Char&gt;" Alias="text"/>
        <Using Include="System.Diagnostics.CodeAnalysis.NotNullAttribute" Alias="NotNullAttribute"/>
    </ItemGroup>

    <!-- global attributes -->
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>ScrubJay.Sandboxes.Console</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>

