namespace ScrubJay.Enums.SourceGen.Factories;

internal static class CommonCode
{
    public static class ExtendAttribute
    {
        public const string TypeFullName = "ScrubJay.Enums.ExtendAttribute";
        
        public const string GeneratedFileName = "ExtendAttribute.g.cs";
        
        public const string Code = """
            /// <auto-generated>Added by ScrubJay.Enums.SourceGen</auto-generated>
            #nullable enable

            namespace ScrubJay.Enums
            {
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                [System.AttributeUsage(System.AttributeTargets.Enum)]
                public sealed class ExtendAttribute : System.Attribute
                {
                }
            }
            """;

        public static readonly GeneratedCode GeneratedCode = new GeneratedCode(GeneratedFileName, Code);
    }
}