using ScrubJay.Enums.SourceGen.Coding;
using ScrubJay.Enums.SourceGen.Models;
using ScrubJay.Enums.SourceGen.Utilities;

namespace ScrubJay.Enums.SourceGen.Factories;

public sealed class UniversalEnumExtensionsGeneratedCodeBuilder : GeneratedCodeBuilder
{
    private readonly EnumToExtend _enumToExtend;

    public UniversalEnumExtensionsGeneratedCodeBuilder(
        EnumToExtend enumToExtend) 
    {
        _enumToExtend = enumToExtend;
    }

    public override GeneratedCode Generate()
    {
        var e2e = _enumToExtend;
        var (enumTypeNamespace, enumTypeName, underlyingType, attributes, members) = e2e;
        var enumTypeFullName = e2e.TypeFullName;
        
        
        var fileName = $"{enumTypeName}Extensions.g.cs";
        using var builder = new CodeBuilder();
        builder.Append($$"""
            /// <auto-generated/>
            #nullable enable

            namespace {{enumTypeNamespace}}
            {
                /// <summary>Extensions on <see cref="{{enumTypeFullName}}"/>.</summary>
                public static partial class {{enumTypeName}}Extensions
                {
                    extension({{enumTypeName}})
                    {
                        public static bool HasFlagsAttribute => {{(e2e.HasFlagsAttribute ? "true" : "false")}};
                        
                        public static Type UnderlyingType => typeof({{underlyingType.FullName}});
                    }
                    
                    extension({{enumTypeName}} @enum)
                    {
                        public string GetName() => @enum switch
                        {
                            {{(insertGetNameCases, members)}}
                        };
                   
                        public {{underlyingType.FullName}} GetValue() => @enum switch
                        {
                            {{(insertGetValueCases, members)}}
                        };
                    
                        public bool Equals({{enumTypeName}} other)
                        {
                            return @enum == other;
                        }
                        
                        public int CompareTo({{enumTypeName}} other)
                        {
                            if (@enum < other)
                                return -1;
                            if (@enum > other)
                                return 1;
                            return 0;
                        }
                    }
                }
            }
            """);
        
        return new(fileName, builder.ToString());
        
        void insertGetNameCases(CodeBuilder b, SGArray<EnumMemberToExtend> ns)
        {
            foreach (var member in ns)
            {
                b.Append($"{enumTypeName}.{member.Name} => nameof({enumTypeName}.{member.Name}),");
                b.NewLine();
            }

            b.Write("_ => @enum.ToString(),");
        }

        void insertGetValueCases(CodeBuilder b, SGArray<EnumMemberToExtend> ns)
        {
            foreach (var member in ns)
            {
                b.Append($"{enumTypeName}.{member.Name} => {member.Value},");
                b.NewLine();
            }

            b.Append($"_ => ((IConvertible)@enum).To{underlyingType.Name}(default),");
        }
    }
}