using ScrubJay.Universal.Extensions;

namespace ScrubJay.Functional.Asp.Extensions;

/// <summary>
/// Extensions on <see cref="Problem"/>
/// </summary>
/// <seealso href="https://datatracker.ietf.org/doc/html/rfc9457"/>
[PublicAPI]
public static class ProblemExtensions
{
    extension(Problem problem)
    {
        /// <summary>
        /// An optional <see href="https://datatracker.ietf.org/doc/html/rfc3986">URI</see> reference that identifies the problem type.
        /// </summary>
        /// <seealso href="https://datatracker.ietf.org/doc/html/rfc9457#name-type"/>
        public string? Type
        {
            get
            {
                if (problem.Data.TryGetValue("type", out var typeObject))
                {
                    if (typeObject.Is<string>(out var strUri))
                        return strUri;
                    if (typeObject.Is<Uri>(out var uri))
                        return uri.ToString();
                }

                return null;
            }
            set
            {
                if (value is not null)
                {
                    problem.Data["type"] = value;
                }
                else
                {
                    problem.Data.Remove("type");
                }
            }
        }
        
        /// <summary>
        /// An optional number indicating the <see href="https://datatracker.ietf.org/doc/html/rfc9110">HTTP</see> <see href="https://datatracker.ietf.org/doc/html/rfc9110#section-15">Status Code</see>
        /// generated by the origin for this problem.
        /// </summary>
        /// <seealso href="https://datatracker.ietf.org/doc/html/rfc9457#name-status"/>
        public int? Status
        {
            get
            {
                if (problem.Data.TryGetValue("status", out var statusObject))
                {
                    if (statusObject.Is<int>(out int statusCode))
                        return statusCode;
                    if (statusObject.Is<int?>(out var optStatusCode))
                        return optStatusCode;
                }
                return null;
            }
            set
            {
                if (value.TryGetValue(out int status))
                {
                    problem.Data["status"] = status;
                }
                else
                {
                    problem.Data.Remove("status");
                }
            }
        }
        
        /// <summary>
        /// An optional URI reference that identifies the specific occurrence of the problem.
        /// </summary>
        /// <seealso href="https://datatracker.ietf.org/doc/html/rfc9457#name-instance"/>
        public string? Instance
        {
            get
            {
                if (problem.Data.TryGetValue("instance", out var typeObject))
                {
                    if (typeObject.Is<string>(out var strUri))
                        return strUri;
                    if (typeObject.Is<Uri>(out var uri))
                        return uri.ToString();
                }

                return null;
            }
            set
            {
                if (value is not null)
                {
                    problem.Data["instance"] = value;
                }
                else
                {
                    problem.Data.Remove("instance");
                }
            }
        }
    }
}