<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ScrubJay.Reflection</RootNamespace>
        <AssemblyName>ScrubJay.Reflection</AssemblyName>

        <!-- Always supports the latest versions -->
        <!-- https://learn.microsoft.com/en-us/dotnet/standard/frameworks#latest-version -->
        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;netstandard2.1;netstandard2.0</TargetFrameworks>
        <CheckEolTargetFramework>false</CheckEolTargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <PolyUseEmbeddedAttribute>true</PolyUseEmbeddedAttribute>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Reflection"/>
        <Using Include="System.Reflection.Emit"/>
        
        <Using Include="ScrubJay.Functional.Prelude" Static="true"/>
    </ItemGroup>
    
    <!-- NuGet Packages -->
    <ItemGroup>
        <PackageReference Include="Fody" Version="6.9.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="InlineIL.Fody" Version="1.10.1">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Polyfill" Version="9.7.3">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    
    <!-- .NetStandard and .NetFramework require extra packages -->
    <ItemGroup Condition=" '$(TargetFramework)' == 'net481' Or '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="System.Memory" Version="4.6.3"/>
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
        <PackageReference Include="System.Reflection.Emit" Version="4.7.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ScrubJay.Core\src\ScrubJay.Core.csproj" />
      <ProjectReference Include="..\..\ScrubJay.Functional\src\ScrubJay.Functional.csproj" />
      <ProjectReference Include="..\..\ScrubJay.Universal\src\ScrubJay.Universal.csproj" />
    </ItemGroup>
</Project>
