<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net48;netstandard2.0;netstandard2.1;net6.0;net7.0;net8.0;net9.0;net10.0;</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>
            $(NoWarn); <!-- inherit -->
            IDE0130;    <!-- Incorrect namespaces -->
        </NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Reflection"/>
        <Using Include="System.Reflection.Emit"/>
        <Using Include="ScrubJay.Reflection.Lightweight"/>
    </ItemGroup>

    <!-- Polyfill layer -->
    <ItemGroup>
        <PackageReference Include="Polyfill"/>
    </ItemGroup>
    <PropertyGroup>
        <!-- Expose all the polyfills to consuming projects -->
        <PolyPublic>true</PolyPublic>
        <!-- Adds Interpolation features from Polyfill -->
        <PolyStringInterpolation>true</PolyStringInterpolation>
        <!-- Add Nullability features from Polyfill -->
        <PolyNullability>true</PolyNullability>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ScrubJay.Reflection.Lightweight\ScrubJay.Reflection.Lightweight.csproj"
                          PrivateAssets="all"/>
    </ItemGroup>

</Project>