<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net48;netstandard2.0;netstandard2.1;net6.0;net7.0;net8.0;net9.0;net10.0;</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>
            $(NoWarn); <!-- inherit -->
            IDE0130;    <!-- Incorrect namespaces -->
        </NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Reflection"/>
        <Using Include="System.Reflection.Emit"/>
        
        <Using Include="InlineIL.IL" Static="true"/>
        <Using Include="Polyfills"/>
        <Using Include="ScrubJay.Polyfills"/>
        
        <Using Include="ScrubJay.Reflection.Lightweight"/>
        <Using Include="ScrubJay.Universal"/>
        <Using Include="ScrubJay.Errors"/>
    </ItemGroup>

    <!-- Polyfill layer -->
    <ItemGroup>
        <PackageReference Include="Polyfill"/>
        <PackageReference Include="Fody" PrivateAssets="all"/>
        <PackageReference Include="InlineIL.Fody" PrivateAssets="all"/>
    </ItemGroup>
    <PropertyGroup>
        <!-- Expose all the polyfills to consuming projects -->
        <PolyPublic>true</PolyPublic>
        <!-- Adds Interpolation features from Polyfill -->
        <PolyStringInterpolation>true</PolyStringInterpolation>
        <!-- Add Nullability features from Polyfill -->
        <PolyNullability>true</PolyNullability>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ScrubJay.Reflection.Lightweight\ScrubJay.Reflection.Lightweight.csproj" PrivateAssets="all"/>
        <ProjectReference Include="..\ScrubJay.Universal\ScrubJay.Universal.csproj" PrivateAssets="all"/>
        <ProjectReference Include="..\ScrubJay.Errors\ScrubJay.Errors.csproj" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Memory\" />
    </ItemGroup>

</Project>