<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="ScrubJay.Universal"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ScrubJay.Reflection.Lightweight\ScrubJay.Reflection.Lightweight.csproj" PrivateAssets="all"/>
        <ProjectReference Include="..\ScrubJay.Universal\ScrubJay.Universal.csproj" PrivateAssets="all"/>
        <PackageReference Include="Polyfill" PrivateAssets="all"/>
    </ItemGroup>

    <PropertyGroup>
        <PolyStringInterpolation>true</PolyStringInterpolation>
        <PolyNullability>true</PolyNullability>
    </PropertyGroup>

</Project>
