<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net10.0;net9.0;net8.0;net48;</TargetFrameworks>
        <SuppressTfmSupportBuildErrors>true</SuppressTfmSupportBuildErrors>
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn);CA2201;CA1515;RS0016;RS0037;</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\ScrubJay.Universal.csproj"/>
    </ItemGroup>

</Project>