<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;netstandard2.1;netstandard2.0;net48;</TargetFrameworks>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- NuGet -->
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>ScrubJay.Text</PackageId>
        <Title>ScrubJay - Text</Title>
        <Description>
            Many utilities for working with text.
        </Description>
        <Version>0.0.1-alpha</Version>
    </PropertyGroup>

    <!-- Global Usings -->
    <ItemGroup>
        <Using Include="InlineIL.IL" Static="true"/>
        <Using Include="InlineIL"/>
        <Using Include="System.Buffers"/>
        <Using Include="ScrubJay.Universal"/>
        <Using Include="ScrubJay.Functional.Prelude" Static="true"/>
        <Using Include="ScrubJay.Functional"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\ScrubJay.Functional\core\ScrubJay.Functional.csproj"/>
        <ProjectReference Include="..\..\ScrubJay.Universal\src\ScrubJay.Universal.csproj"/>

        <PackageReference Include="Fody">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="InlineIL.Fody">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <!--        <PackageReference Condition="'$(TargetFramework)' == 'netstandard2.1' "-->
        <!--                          Include="System.Runtime.CompilerServices.Unsafe">-->
        <!--            <PrivateAssets>all</PrivateAssets>-->
        <!--        </PackageReference>-->

    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'netstandard2.1' or '$(TargetFramework)' == 'net48'">
        <PackageReference Include="System.Memory"/>
        <PackageReference Include="Microsoft.Bcl.Memory"/>
    </ItemGroup>

    <!-- Expose our internals -->
    <ItemGroup>
        <InternalsVisibleTo Include="ScrubJay.Text.Tests"/>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Building\" />
    </ItemGroup>

</Project>
