<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;netstandard2.1;netstandard2.0;net48</TargetFrameworks>
        <CheckEolTargetFramework>false</CheckEolTargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <NoWarn>$(NoWarn);CS1591;</NoWarn>
    </PropertyGroup>

    <!-- Global Usings -->
    <ItemGroup>
        <Using Include="ScrubJay.Functional.Prelude" Static="true"/>
        <Using Include="ScrubJay.Functional"/>
        <Using Include="ScrubJay.Universal"/>

        <Using Include="ScrubJay.Enhancements.Extensions"/>
        <Using Include="ScrubJay.Enhancements.Text"/>
        <Using Include="ScrubJay.Enhancements.Exceptions"/>
        <Using Include="ScrubJay.Enhancements.Utilities"/>


    </ItemGroup>


    <!-- NuGet -->
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>ScrubJay.Enhancements</PackageId>
        <Title>ScrubJay - Enhancements</Title>
        <Description>
            Common enhancements to C# that are useful in any sort of project.
        </Description>
        <Version>0.1.0-alpha</Version>
    </PropertyGroup>

    <!-- Expose our internals to Benchmarks, BuildTasks, Tests, and downstream ScrubJay libraries -->
    <ItemGroup>
        <InternalsVisibleTo Include="ScrubJay.Enhancements.Benchmarks"/>
        <InternalsVisibleTo Include="ScrubJay.Enhancements.BuildTasks"/>
        <InternalsVisibleTo Include="ScrubJay.Enhancements.Tests"/>

        <InternalsVisibleTo Include="ScrubJay.Sandboxes.Console"/>
    </ItemGroup>

    <!-- Project and Package references -->
    <ItemGroup>
        <ProjectReference Include="..\..\ScrubJay.Functional\src\ScrubJay.Functional.csproj"/>
        <ProjectReference Include="..\..\ScrubJay.Universal\src\ScrubJay.Universal.csproj"/>

        <PackageReference Include="Fody">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="InlineIL.Fody">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        
        <PackageReference Include="Polyfill">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <!-- .NetStandard and .NetFramework require extra packages -->
    <ItemGroup Condition=" '$(TargetFramework)' == 'net481' Or '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1'">
        <PackageReference Include="System.Memory"/>
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <!-- MSBuild Tasks -->
    <UsingTask
            TaskName="GenerateGuardPartsBuildTask"
            AssemblyFile="$(MSBuildProjectDirectory)\..\build\bin\$(Configuration)\netstandard2.0\ScrubJay.Enhancements.BuildTasks.dll"/>

    <Target Name="GenerateValidateFiles" BeforeTargets="BeforeBuild">
        <ItemGroup>
            <ValidateFiles Include="**\Validate*.cs" Exclude="bin\**;obj\**;"/>
        </ItemGroup>

        <GenerateGuardPartsBuildTask ValidateParts="@(ValidateFiles)"/>
    </Target>
</Project>
