<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <!-- <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;</TargetFrameworks> -->
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ScrubJay.Sandboxes</RootNamespace>
        <AssemblyName>ScrubJay.Sandboxes.Console</AssemblyName>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Diagnostics"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="System.Text.Json" />
        <ProjectReference Include="..\ScrubJay.Core\src\ScrubJay.Core.csproj"/>
        <ProjectReference Include="..\ScrubJay.Enums\src\ScrubJay.Enums.csproj" />
        <ProjectReference Include="..\ScrubJay.Functional\asp\ScrubJay.Functional.Asp.csproj"/>
        <ProjectReference Include="..\ScrubJay.Functional\json\ScrubJay.Functional.Json.csproj"/>
        <ProjectReference Include="..\ScrubJay.Functional\src\ScrubJay.Functional.csproj"/>
        <ProjectReference Include="..\ScrubJay.Reflection\src\ScrubJay.Reflection.csproj"/>
        <ProjectReference Include="..\ScrubJay.Universal\src\ScrubJay.Universal.csproj"/>

        <PackageReference Include="Fody">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="InlineIL.Fody">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <ProjectReference Include="..\ScrubJay.Universal\tests\ScrubJay.Universal.Tests.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Demand*.cs"/>
    </ItemGroup>

</Project>
