<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ScrubJay.Sandboxes</RootNamespace>
        <AssemblyName>ScrubJay.Sandboxes.Console</AssemblyName>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Diagnostics"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ScrubJay.Core\src\ScrubJay.Core.csproj" />
        <ProjectReference Include="..\ScrubJay.Functional\asp\ScrubJay.Functional.Asp.csproj" />
        <ProjectReference Include="..\ScrubJay.Functional\json\ScrubJay.Functional.Json.csproj" />
        <ProjectReference Include="..\ScrubJay.Functional\src\ScrubJay.Functional.csproj"/>
        <ProjectReference Include="..\ScrubJay.Reflection\src\ScrubJay.Reflection.csproj" />
        <ProjectReference Include="..\ScrubJay.Universal\src\ScrubJay.Universal.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Demand*.cs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Polyfill">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
