<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\core\ScrubJay.Functional.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <!-- NuGet -->
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>ScrubJay.Functional.Asp</PackageId>
        <Title>ScrubJay - Functional for ASP</Title>
        <Description>
            ASP helpers for ScrubJay.Functional
        </Description>
        <Version>0.91.0-alpha</Version>
    </PropertyGroup>

</Project>
