<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Using Include="System.Reflection"/>
        <Using Include="System.Reflection.Emit"/>
        <Using Include="InlineIL.IL" Static="true"/>
        <Using Include="Polyfills"/>
        <Using Include="ScrubJay.Polyfills"/>
        <Using Include="ScrubJay.Memory"/>
        <Using Include="ScrubJay.Text"/>
    </ItemGroup>

    <!-- NuGet Packages -->
    <ItemGroup>
        <PackageReference Include="Fody" PrivateAssets="all"/>
        <PackageReference Include="InlineIL.Fody" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="System.Reflection.Emit"/>
        <PackageReference Include="System.Reflection.Emit.Lightweight"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ScrubJay.Errors\ScrubJay.Errors.csproj" />
      <ProjectReference Include="..\ScrubJay.Functional\ScrubJay.Functional.csproj" />
      <ProjectReference Include="..\ScrubJay.Memory\ScrubJay.Memory.csproj" />
      <ProjectReference Include="..\ScrubJay.Polyfills\ScrubJay.Polyfills.csproj" />
      <ProjectReference Include="..\ScrubJay.Reflection.Lightweight\ScrubJay.Reflection.Lightweight.csproj" />
      <ProjectReference Include="..\ScrubJay.Text\ScrubJay.Text.csproj" />
      <ProjectReference Include="..\ScrubJay.Universal\ScrubJay.Universal.csproj" />
    </ItemGroup>

</Project>