/// <auto-generated>Added by ScrubJay.Enums.SourceGen</auto-generated>
#nullable enable

namespace ScrubJay.Enums
{
    [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
    [System.AttributeUsage(System.AttributeTargets.Enum)]
    public sealed class ExtendAttribute : System.Attribute
    {
    }
}