/// <auto-generated/>
#nullable enable

namespace ScrubJay.Sandboxes.Console
{
    /// <summary>Extensions on <see cref="ScrubJay.Sandboxes.Console.TestEnum"/>.</summary>
    public static partial class TestEnumExtensions
    {
        extension(TestEnum)
        {
            public static bool HasFlagsAttribute => true;
            
            public static Type UnderlyingType => typeof(System.Int32);
        }
        
        extension(TestEnum @enum)
        {
            public string GetName() => @enum switch
            {
                TestEnum.Zero => nameof(TestEnum.Zero),
                TestEnum.One => nameof(TestEnum.One),
                TestEnum.Two => nameof(TestEnum.Two),
                TestEnum.Four => nameof(TestEnum.Four),
                TestEnum.Eight => nameof(TestEnum.Eight),
                TestEnum.Sixteen => nameof(TestEnum.Sixteen),
                _ => @enum.ToString(),
            };
       
            public System.Int32 GetValue() => @enum switch
            {
                TestEnum.Zero => 0,
                TestEnum.One => 1,
                TestEnum.Two => 2,
                TestEnum.Four => 4,
                TestEnum.Eight => 8,
                TestEnum.Sixteen => 16,
                _ => ((IConvertible)@enum).ToInt32(default),
            };
        
            public bool Equals(TestEnum other)
            {
                return @enum == other;
            }
            
            public int CompareTo(TestEnum other)
            {
                if (@enum < other)
                    return -1;
                if (@enum > other)
                    return 1;
                return 0;
            }
        }
    }
}