<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

    </PropertyGroup>

    <!-- NuGet -->
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>ScrubJay.Functional</PackageId>
        <Title>ScrubJay - Functional</Title>
        <Description>
            Functional types and extensions for C#.
        </Description>
        <Version>0.91.0-alpha</Version>
    </PropertyGroup>

    <!-- Global Usings -->
    <ItemGroup>

    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ScrubJay.Errors\ScrubJay.Errors.csproj" />
        <ProjectReference Include="..\ScrubJay.Polyfills\ScrubJay.Polyfills.csproj"/>
        <ProjectReference Include="..\ScrubJay.Universal\ScrubJay.Universal.csproj" />
    </ItemGroup>

</Project>
