<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PolyNullability>true</PolyNullability>
    </PropertyGroup>

    <!-- NuGet -->
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>ScrubJay.Functional</PackageId>
        <Title>ScrubJay - Functional</Title>
        <Description>
            Functional types and extensions for C#.
        </Description>
        <Version>0.91.0-alpha</Version>
    </PropertyGroup>

    <!-- Global Usings -->
    <ItemGroup>
        <Using Include="ScrubJay.Functional.Prelude" Static="true"/>
        <!--        <Using Include="Polyfills"/>-->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ScrubJay.Debugging\ScrubJay.Debugging.csproj"/>
        <ProjectReference Include="..\ScrubJay.Reflection.Lightweight\ScrubJay.Reflection.Lightweight.csproj"/>
        <ProjectReference Include="..\ScrubJay.Universal\ScrubJay.Universal.csproj"/>

        <PackageReference Include="Polyfill" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Utilities\"/>
    </ItemGroup>

</Project>
