<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <!--        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;netstandard2.1;netstandard2.0;net48;</TargetFrameworks>-->
        <TargetFramework>net10.0</TargetFramework>

        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>.GeneratedFiles</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Polyfill">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>

        <ProjectReference Include="..\..\ScrubJay.Enums\src\ScrubJay.Enums.csproj"/>

        <ProjectReference Include="..\..\ScrubJay.Errors\asp\ScrubJay.Errors.Asp.csproj" />
        <!--        <ProjectReference Include="..\..\ScrubJay.Functional\asp\ScrubJay.Functional.Asp.csproj"/>-->
        <ProjectReference Include="..\..\ScrubJay.Errors\src\ScrubJay.Errors.csproj"/>
        <ProjectReference Include="..\..\ScrubJay.Functional\core\ScrubJay.Functional.csproj"/>
        <ProjectReference Include="..\..\ScrubJay.Text\src\ScrubJay.Text.csproj"/>
        <!--        <ProjectReference Include="..\..\ScrubJay.Functional\json\ScrubJay.Functional.Json.csproj"/>-->
        <ProjectReference Include="..\..\ScrubJay.Universal\src\ScrubJay.Universal.csproj"/>

        <!--        <ProjectReference-->
        <!--                Include="..\..\ScrubJay.Enums\srcgen\ScrubJay.Enums.SourceGen.csproj"-->
        <!--                ReferenceOutputAssembly="false"-->
        <!--                OutputItemType="Analyzer"/>-->
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="System.Reflection.Emit">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

</Project>
