<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <!-- Common to all Projects -->

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;netstandard2.1;netstandard2.0;net48;</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- Ignore old versions -->
        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
        <CheckEolTargetFramework>false</CheckEolTargetFramework>

        <!-- Generate XML documentation -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <!-- NuGet -->
    <PropertyGroup>
        <!-- Each project itself will specify PackageId, PackageVersion, Description, -->
        <Authors>Dissolution</Authors>
        <RepositoryUrl>https://github.com/Dissolution/ScrubJay</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
</Project>
