<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>

    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>
            $(NoWarn); <!-- inherit -->
        </NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Reflection"/>
        <Using Include="System.Reflection.Emit"/>
        <Using Include="ScrubJay.Reflection.Lightweight"/>
        <Using Include="InlineIL.IL" Static="true"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ScrubJay.Reflection.Lightweight\ScrubJay.Reflection.Lightweight.csproj" PrivateAssets="all"/>
        
        <PackageReference Include="Nullable" PrivateAssets="all"/>
        <PackageReference Include="Fody" PrivateAssets="all"/>
        <PackageReference Include="InlineIL.Fody" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="ARCHIVE\"/>
    </ItemGroup>

</Project>